### ISSUE TITLE
Converted map is corrupted.

### ISSUE THREAD

**Issue by legoboy0215** [ljyloo/LevelDb2Avnil#10]
the title says it all. I will show you the error later. Some thing about gzip?

**Comment by legoboy0215** [comment]
Hello?

**Comment by ljyloo** [comment]
@legoboy0215 Your map may contain some blocks which are not exist in MCPC

**Comment by legoboy0215** [comment]
Oh ok :) Thanks!

**Comment by ljyloo** [comment]
@legoboy0215 I have tried to write a filter before, but it's a lot of work to do, so I give up

**Comment by legoboy0215** [comment]
:) It is ok. You are the only one who made this tool. I appreciate it :)
