### ISSUE TITLE
Minecraft PE 1.0.0 worlds are not supported

### ISSUE THREAD

**Issue by Aphys122** [ljyloo/LevelDb2Avnil#15]
"Worldanvil" folder is empty after convertation

**Comment by ljyloo** [comment]
This codes is outdated:(

**Comment by Aphys122** [comment]
Will you support MCPE 1.0.0 in the future?

**Comment by ljyloo** [comment]
no plan. I am working on neural network and think it's more funny than minecraft:)

**Comment by ankitmaharjan252** [comment]
I got it working and it just converted the half of the chunk of my world!
What can I change so it converts all the chunk?

**Comment by ili-codes** [comment]
Is there any other app to do this?

**Comment by Aphys122** [comment]
@ljyloo, thanks for updating converter! It's amazing!
