### ISSUE TITLE
Suggestion: supporting mixed worlds

### ISSUE THREAD

**Issue by Aphys122** [ljyloo/LevelDb2Avnil#16]
I think it will be very cool to do support for the "mixed" worlds, with chunks created by mcpe 0.9 - 0.16 and mcpe 1.0+, because I have world created a long time ago with Minecraft PE 0.9.5, and I still play on it. Now I use MCPE 1.0.0.16, and latest version of converter converts only chunks edited with PE 1.0.0.16, but I want to convert a whole world!

**Comment by ljyloo** [comment]
Thanks for advice. I didn't think of this kind of situation:P
But I don't have a sample like your world, can you send me your world to do some experiment?
You can send me via [twitter message](https://twitter.com/ljyloo)

**Comment by Aphys122** [comment]
@ljyloo, here is a world: https://drive.google.com/file/d/0BwOOqz-zuiraeHRNVXF0QmgxMm8/view?usp=drive_web
This world is HUGE (it takes about 1GB of disk memory), but I think you can deal with it. For better navigation in my world, you can use this online map: https://metrogradmap.github.io
(Sorry for my bad English)

**Comment by Aphys122** [comment]
@ljyloo, your spawn point will be here:
![spawn](https://user-images.githubusercontent.com/24764736/27187446-e78cfbd4-51f3-11e7-95e6-e5654056a260.png)
There is areas of my world edited with different versions of MCPE:
![areas](https://user-images.githubusercontent.com/24764736/27187590-4ac91fde-51f4-11e7-86ab-c32755d47add.png)

**Comment by ljyloo** [comment]
Wow, you built a amazing map... Thanks for your data!

**Comment by ljyloo** [comment]
Combine with #7
