### ISSUE TITLE
Bug with block's IDs

### ISSUE THREAD

**Issue by Aphys122** [ljyloo/LevelDb2Avnil#17]
Some blocks were incorrectly converted:
Grass Path became the Ender Rod (and Ender rod in MCPE became Grass Path in PC after convertation):
![screenshot-2017-06-15-18-47_2](https://user-images.githubusercontent.com/24764736/27190025-d387ce68-51fb-11e7-9a6f-e1d2372dada7.png)
![idbug3](https://user-images.githubusercontent.com/24764736/27190035-de7daeb4-51fb-11e7-87a7-007eb91a8eaf.png)
Quartz slab became Nether brick slab:
![screenshot-2017-06-15-18-47](https://user-images.githubusercontent.com/24764736/27190190-56cbc5fe-51fc-11e7-82a5-7669fe4eabe3.png)
![idbug2](https://user-images.githubusercontent.com/24764736/27190201-5f52b476-51fc-11e7-8f88-4f23bddb6070.png)
Oak slab became Dropper:
![screenshot-2017-06-15-18-46](https://user-images.githubusercontent.com/24764736/27190249-856880be-51fc-11e7-8b92-bbcc802e22e6.png)
![idbug1](https://user-images.githubusercontent.com/24764736/27190257-8e8a0852-51fc-11e7-8a72-5455ce90d42d.png)

**Comment by ljyloo** [comment]
Thanks for your discovery! I'll fix that in the next commit

**Comment by ljyloo** [comment]
By the way, if you found more wrong ID translation keep report at here:) Really appreciated

**Comment by Aphys122** [comment]
@ljyloo, Okay, good luck in working it out!😄

**Comment by ljyloo** [comment]
Fix in the lastest commit fdcc3dc

**Comment by ljyloo** [comment]
I took about 20 minutes to convert your map, and I upload to Google Drive. [https://drive.google.com/file/d/0BypKaIhTUMcfNi1BTmRLOUMxeWc/view?usp=sharing](here)

**Comment by Aphys122** [comment]
Thanks for update! I'll test it tomorrow.

**Comment by Aphys122** [comment]
@ljyloo, your converter works perfectly! Thanks for this unique app!
