### ISSUE TITLE
Does nothing.

### ISSUE THREAD

**Issue by thebigsmileXD** [ljyloo/LevelDb2Avnil#18]
![image](https://user-images.githubusercontent.com/8733998/27285799-20980cf4-54fe-11e7-98a4-9975887cec6b.png)
Correct folders are given. Trying to convert PC 1.8 to MCPE

**Comment by ljyloo** [comment]
What version are you using?

**Comment by thebigsmileXD** [comment]
the SRC, freshly downloaded. Don't need this anyways i just realized pmmp supports anvil
