### ISSUE TITLE
Conversion "done" but no export folder/files generated on windows 7 !

### ISSUE THREAD

**Issue by roroB20** [ljyloo/LevelDb2Avnil#2]
When using this tool on windows 7 to import a leveldb world from MCPE 0.10.5 to convert it into anvil . When starting the batch file we can see "done !" message on the Command Prompt but there is no folder generated or files from this conversion.

Update : When using last commit I get this error : 

Exception in thread "main" java.lang.NullPointerException
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:233)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)

**Comment by ljyloo** [comment]
Can you tell me how you use it?like the command you use and the instruction of the import folder

**Comment by roroB20** [comment]
1- I download the last "Converter.jar" on github !
2- I create a folder on C: root to relocate the jar file (example "leveldbconverter") and two folders for import/export into it (example myworld and myworldAnvil).
3- I create a batch file using as indicated in readme file with a code like this : 
java -jar Converter.jar \leveldbconverter\myworld \leveldbconverter\myworldAnvil
pause
4-I start the batch file and get this error:

C:\leveldbconverter>java -jar Converter.jar \leveldbconverter\myworld \leveldbco
nverter\myworldAnvil
Exception in thread "main" java.lang.NullPointerException
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:233)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)

**Comment by ljyloo** [comment]
The commands you wrote in the batch file is wrong, I think. Try this one "C:\leveldbconverter>java -jar Converter.jar C:\leveldbconverter\myworld C:\leveldbconverter\myworldAnvil"

**Comment by ljyloo** [comment]
@roroB20 And make sure there a complete structure in folder "myworld", look at the picture
![folder](https://cloud.githubusercontent.com/assets/5047573/6768025/113e7f78-d08e-11e4-911a-ace11042ed14.png)

**Comment by roroB20** [comment]
Yes it's the same structure (I've copied my world directly from MCPE) and I tried your commands : "java -jar Converter.jar C:\leveldbconverter\myworld C:\leveldbconverter\myworldAnvil" but I get the same error :/ !

I share here a link from dropbox to download a zip file containing the main folder "leveldbconverter" (to copy it into C: ) if you want to make a test ;) !

https://www.dropbox.com/s/qdq45rldnzks1hy/leveldbconverter.zip?dl=0

**Comment by ljyloo** [comment]
@roroB20 I tested it and successfully converted your map.I just open a CMD window and use command "java -jar Converter.jar myworld myworldanvil"

**Comment by roroB20** [comment]
Ohh...So I don't know why it doesn't work with me ...XD ! Maybe the java version is implicated in this problem ? What version of java is installed on your PC ?? Because I have Java 8 update 25 (build 1.8.0_25-b18) already installed on windows 7 and I always get this error for any commands I use :/ !

**Comment by ljyloo** [comment]
@roroB20 Hmm....I use Java7 and my system is Window8.1 pro

**Comment by roroB20** [comment]
Can you try to install java 8 to see if you get the same error ?

**Comment by ljyloo** [comment]
@roroB20 No, I tested on jre-8u40 and get no error

**Comment by roroB20** [comment]
@ljyloo So what's the origin of the problem ? I don't understand why I always getting the same error and I'm looking for a solution because your tool seems to me extremely useful ^^!

**Comment by ljyloo** [comment]
@roroB20 I have no idea. Maybe you can give me your map and I help you convert it ;)

**Comment by roroB20** [comment]
Humm...that's might be a temporary solution XD ! And thank you for spending time to help me with this strange problem :)
I will try to find why my PC is so heretical :P ! ( I always want to know why things that should work finally refuses to work as intended ^^ )

Here the link of the LevelDB world I need to convert ;) : 
https://www.dropbox.com/s/bk8u8fea04u66g9/Leveldb_world.zip?dl=0

**Comment by ljyloo** [comment]
Ok, here https://www.dropbox.com/s/zqbzv44r4n5o705/out.rar?dl=0

**Comment by roroB20** [comment]
@ljyloo Thank you so much for the map :D ! I will try the converter on others PC for trying to determinate what's the problem ! I'll keep you informed if I find something ;)

PS: Are you always working on your Portal plugin ? And if so would you interested by working on the @Comedyman937 project: MultiversePE  ?
I've thought that if you are interested by contributing to his project your knowledge about programming portals might be very helpful for developping an awsome port of the Multiverse bukkit's plugin :)  

Here the link of MultiversePE project : https://github.com/Comedyman937/MultiversePE

**Comment by goerick** [comment]
Works on windows 7 64 architecture with latest java

**Comment by roroB20** [comment]
Nope ! XD I have Windows7x64 and latest java and I get the error ! That's why it's a mystery ;)

**Comment by fankins** [comment]
Don`t work! I have error <code>Exception in thread "main" java.lang.NullPointerException
at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:233)
at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)</code>
or 'Done' but no export folder/files generated.

**Comment by ljyloo** [comment]
@fankins What system do you use?

**Comment by roroB20** [comment]
@ljyloo So confirmed on windows 8.1x64 :/ ! Can try to find what are the components necessary (or installed on your computer) to run the converter (Example: java, visual C++ , directX ...).

**Comment by ljyloo** [comment]
@roroB20 LOL

**Comment by roroB20** [comment]
Hummmm...so other ideas ? XD

**Comment by Johnmacrocraft** [comment]
Hey liyloo can you convert my map to run at PocketMine-MP too? I'm getting same error so I need to ask like him.
My Map URL is:
https://www.dropbox.com/s/9l37sluwtji2413/My%20Maps.zip?dl=0
Please download and convert my map. I want to open server with my map.

**Comment by goerick** [comment]
Do it yourself @johnmacrocraft not that hard seriously people. Update your java Or change your OS :/

**Comment by goerick** [comment]
Remember to have the src and put it all in one folder

**Comment by minecrafter2016** [comment]
Hi all,
Sorry to revive such an old thread but I just encountered this exact error with my attempted conversion.  I am not sure it is a system issue/setting because I have been converting earlier versions of this same world without errors but then today when I did it (without updating or changing any settings whatsoever) it threw up that same error:
Exception in thread "main" java.lang.NullPointerException
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:233)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)

I am using the latest version of your cool software (May 21, 2016) with Windows 7 x64, Java 8 Update 73 (64-bit), but as I've said, the most prior successful conversion was done just hours earlier on the same world.
ljyloo, can you please help me out?

roroB20, did you ever find more info or figure out what the problem was?  I tried converting your world (above) and got the same error. :(

**Comment by ljyloo** [comment]
Check out #13

**Comment by minecrafter2016** [comment]
Hi @ljyloo , I'm sorry I don't quite understand the connection with that other issue you linked to.  My error is different.  I don't believe this is an issue with file location or folder structure as I have been doing the exact same thing successfully several times before with the same world with no hiccups.  It is just this latest version of my world that it's having problems with. (??)
If I misunderstood you please explain it to me as if I were a total newbie.  Thank you. :)

**Comment by minecrafter2016** [comment]
Hi, I read that you can convert LevelDB to Anvil using MCEdit.  I tried opening an earlier version of my world in it with no issue.  However, when I tried the latest version, that I've been posting about here, it also gave me an error.  I know this forum isn't support for MCEdit but I was hoping someone here understands the error so maybe can help me fix or get around this.  Maybe the error might mean a single "config" file is corrupted and I can just replace that file?  Any help is much appreciated!

![mcedit_error_opening_wonderland-latest](https://cloud.githubusercontent.com/assets/19632624/15663225/89d0fd3c-26c6-11e6-826b-89d9558ea8d6.png)

**Comment by ljyloo** [comment]
@minecrafter2016 Maybe the latest version of MCPE changed the structure of the container with map data(which is so called LevelDB in MCPE, Anvil in MCPC), and my code can't handle it(unless I do some experiment to find out what did they change and rewrite the code).

**Comment by minecrafter2016** [comment]
@ljyloo Though that's possible why did roroB20 encounter the same error (albeit in 2015)?  I've been poking around the web and forums all over for days trying to find how to fix this.  Would it be too much to ask if you can try converting my world files for me?  I can put it on Dropbox for you.  The last conversion took just 1-2 minutes.
