### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wjrlxa** [ljyloo/LevelDb2Avnil#21]
E:\1\2\LevelDb2Avnil-master>java -jar Converter.jar world worldanvil
Converting legacy chunk X: 0 Z: 9Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:139)
        at com.ljyloo.PE2PC.ConvertSource.convertLegacyTerrain(ConvertSource.java:211)
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:111)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:37)

**Comment by wjrlxa** [comment]
I tried using the old version and the conversion was successful. But some of the box conversions have gone wrong. such as:
![image](https://user-images.githubusercontent.com/7100522/28601307-0dbc0988-71ea-11e7-8316-d24f4c015f42.png)
![image](https://user-images.githubusercontent.com/7100522/28601334-3c5da7a6-71ea-11e7-9802-88c4987a1fbf.png)

**Comment by misssalad612** [comment]
Sorry, it was a carelessness. Could you send me your map to let me test?

**Comment by misssalad612** [comment]
my twitter @misssalad612

**Comment by wjrlxa** [comment]
please give me ur email
@misssalad612

**Comment by misssalad612** [comment]
cindejze412@gmail.com

**Comment by wjrlxa** [comment]
Sorry, I downloaded three versions of the computer version of minecraft, the conversion is normal. The reason for the box error may be due to Nukkit
@misssalad612

**Comment by misssalad612** [comment]
It's OK. I'm glad to know this program works well for you :), and you actually let me find a bug. Thanks.

**Comment by wjrlxa** [comment]
Thank you~
