### ISSUE TITLE
Unknow Key and ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by peter-4A5A** [ljyloo/LevelDb2Avnil#23]
When i try to convert a minecraft PE map to PC it gives me the following error:
Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 047 003

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 047 004

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 047 005

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 047 006

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 047 007

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 054

Unknown Key:
0x023 000 000 000 -21 -01 -01 -01 001 000 000 000 118

Unknown Key: gacy chunk X: 65 Z: -11
0x065 117 116 111 110 111 109 111 117 115 069 110 116 105 116 105 101 115

Unknown Key: gacy chunk X: 66 Z: -12
0x066 105 111 109 101 068 097 116 097

Converting legacy chunk X: 78 Z: -1Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:88)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:37)

**Comment by misssalad612** [comment]
I have uploaded a new version jar which should fix this problem :)

**Comment by peter-4A5A** [comment]
It fixed the Unknown Key issue, but it didn't fixed this issue: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:88)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:34)

**Comment by misssalad612** [comment]
I think i know where is wrong...working on it. My bad :(

**Comment by peter-4A5A** [comment]
Oooh, no problem good luck fixing it!

**Comment by misssalad612** [comment]
Wow

**Comment by bwburnsides** [comment]
I'm having the exact same issue, any progress on fixing it?
