### ISSUE TITLE
SUGGESTION: Use maven for dependencies

### ISSUE THREAD

**Issue by jython234** [ljyloo/LevelDb2Avnil#3]
Title says all.

**Comment by ljyloo** [comment]
@jython234 XD, but I don't know how to use maven

**Comment by jython234** [comment]
I can teach you. My project BlockServer hosts a maven repository which
includes the same LevelDB library you use.

On Wednesday, April 1, 2015, LittleBlackBird <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> XD, but I don't know how to use
> maven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ljyloo/LevelDb2Avnil/issues/3#issuecomment-88532327>.
>


--

**Comment by goerick** [comment]
:0

**Comment by ljyloo** [comment]
@jython234 So, how to use maven?;)

**Comment by jython234** [comment]
@LittleBlackBird, it would be easier to Discuss this on IRC. My timezone is
GMT -6, or US Central Time. I am available at 4-5:30 pm, on irc.freenode.net
channel is #blockserverproject.
On Wednesday, April 1, 2015, LittleBlackBird <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> So, how to use maven?;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ljyloo/LevelDb2Avnil/issues/3#issuecomment-88713515>.
>


--

**Comment by ljyloo** [comment]
@jython234 Got it;)
