### ISSUE TITLE
Are you sure it works with Minecraft PE 1.2.1?

### ISSUE THREAD

**Issue by Camiga** [ljyloo/LevelDb2Avnil#34]
I copied over a Minecraft PE 1.2.1 world from my iPad 4th generation running iOS 10.3.3, and this is what appears in the log. The CMD window opens up for about a second before closing again, even after I tried executing it with the Java command. A lot of other people are also saying that it doesn't work with Minecraft 1.2.1.
[log.txt](https://github.com/ljyloo/LevelDb2Avnil/files/1358020/log.txt)

**Comment by KerbalFun123** [comment]
WHY WONT ANYONE EXPLAIN!?

**Comment by misssalad612** [comment]
This program seems not working on Minecraft PE 1.2.x since the way to access map files had been changed in this version.

**Comment by KerbalFun123** [comment]
Okay, can that be fixed?

**Comment by misssalad612** [comment]
Working on it.
