### ISSUE TITLE
It Gives Me An .MCA File What Do I Do

### ISSUE THREAD

**Issue by MCPotatoCraft** [ljyloo/LevelDb2Avnil#4]
What do i do with an mca file

**Comment by ljyloo** [comment]
You can create a MC map then put it into that folder

**Comment by MCPotatoCraft** [comment]
I did that it doesn't show the map

**Comment by MCPotatoCraft** [comment]
what about the level.dat

**Comment by goerick** [comment]
You generate a new world and replace that region folder with your mca

**Comment by MCPotatoCraft** [comment]
I did what goerick and ljyloo said here is the world file http://tiny.cc/pkqiyx

**Comment by ljyloo** [comment]
@MCPotatoCraft And what's the problem?

**Comment by MCPotatoCraft** [comment]
It shows the flat world I put the Mca files in

**Comment by ljyloo** [comment]
@MCPotatoCraft You need to get to the correct coordinate

**Comment by MCPotatoCraft** [comment]
what are those

**Comment by goerick** [comment]
Look it up
