### ISSUE TITLE
World not exported

### ISSUE THREAD

**Issue by RekkuzaRage** [ljyloo/LevelDb2Avnil#5]
For some reason, my world isn't exported. No error messages appear. Just a "done." message.

root@pm:~# java -jar Converter.jar /home/dannyg/DG /home/dannyg/s2/worlds/DG
Done!

**Comment by goerick** [comment]
There should be mca files

**Comment by ljyloo** [comment]
Have your folders been created?If they are not exist, please create them then try again

**Comment by ljyloo** [comment]
BTW, the input folder should contain a folder name "db" and a file name "level.dat".The folder "db" contains some files, such as "00xxxx.ldb", "00xxxx.log", "CURRENT", "LOCK", "LOG", "MANIFEST-00xxxx"."xxxx" means random nembers

**Comment by billym357** [comment]
@ljyloo I created the folders. But the program doesn't even open up when clicking on it. Is there anyway you could create a user friendly GUI?

**Comment by ljyloo** [comment]
@billym357 read README.md please
