### ISSUE TITLE
Overthinking..?

### ISSUE THREAD

**Issue by tiNsLeY799** [ljyloo/LevelDb2Avnil#6]
I'm just starting out in programming, so I'm illiterate when it comes to this.. I understand the java -jar Converter.jar it's just the folders that are really kicking me. I put the LevelDBtoAnbil folder in the root (because I thought maybe I did something wrong?) but I'm not really sure what I'm doing. Please help, much is appreciated!

**Comment by ljyloo** [comment]
Absolute or relatively path is ok :)

**Comment by tiNsLeY799** [comment]
Ok thank you! It works now, but I know it only functions with it's proper level.dat
