### ISSUE TITLE
Doesn't do anything when trying to open it

### ISSUE THREAD

**Issue by billym357** [ljyloo/LevelDb2Avnil#8]

**Comment by Heromine** [comment]
i tried and it doesn't do anything. It says "Done" whitout output files...same error of the others.
I am on Windows 7 x86 java 8.
I followed all the instructions, and anything happens

**Comment by ljyloo** [comment]
See #5

**Comment by Heromine** [comment]
@ljyloo so?  I knew it, it is the same

**Comment by ljyloo** [comment]
@Heromine No, I mean you should read my comment there

**Comment by Heromine** [comment]
@ljyloo I did it

**Comment by ljyloo** [comment]
@Heromine Did you follow my instruction?

**Comment by Heromine** [comment]
@ljyloo yes all

**Comment by ljyloo** [comment]
@Heromine If you don't mind, can you send me your map?I have a try
