### ISSUE TITLE
Import Folder Problem: Doesnt Exist

### ISSUE THREAD

**Issue by Fang100101** [ljyloo/LevelDb2Avnil#9]
When ever I try to run the program it always says the the import folder doesn't exist. I know for sure that the folder DOES exist and that my path is correct! What am I doing wrong?
![leveldb2anvil problem](https://cloud.githubusercontent.com/assets/13601513/9022221/c782bf2c-3832-11e5-9c72-f4ac52d1ee37.png)

**Comment by Fang100101** [comment]
@ljyloo Do you have any ideas?

**Comment by ljyloo** [comment]
Give me a snapshot of your folder
